In [21]:
#01.선형회귀
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
torch.manual_seed(1)

In [22]:
x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[4],[5],[6]])
# 데이터에 대한 이해 -> 가설 수립-> 손실 계산하기-> 경사 하강법
# 비용 함수(cost function) = 손실 함수(loss function) = 오차 함수(error function) = 목적 함수(objective function)



In [23]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [24]:
print(y_train)
print(y_train.shape)

tensor([[4.],
        [5.],
        [6.]])
torch.Size([3, 1])


In [25]:
W=torch.zeros(1,requires_grad=True) # requir~는 인자로 주어졌으며, 이 변수는 학습을 통해 값이 게속 변경되는 변수임을 명시
print(W)
b=torch.zeros(1,requires_grad=True) #requires_grad라는 속성은 자동미분기능 속성입니다. 선형 회귀부터 신경망같은 복잡한 구조에서 파라미터들이 모두 이 기능이 적용됩니다.
print(b)
# 현재 직선의 방정식은 y=0*x+0

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [26]:
hypothesis=x_train*W+b
print(hypothesis)
cost=torch.mean((hypothesis-y_train)**2)
print(cost) #grad_fn=<MeanBackward0> 는 뭐임?


tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)
tensor(25.6667, grad_fn=<MeanBackward0>)


In [27]:
optimizer=optim.SGD([W,b],lr=0.01) # W와 b를 SGD의 입력으로 설정
optimizer.zero_grad() #gradient 0으로 초기화
cost.backward() #cost함수를 이용하여 gradient 계산 
optimizer.step() #W와 b를 업데이트


In [28]:
nb_epochs=2000
for epoch in range(nb_epochs+1):
    hypothesis=x_train*W+b
    cost=torch.mean((hypothesis-y_train)**2)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    if epoch %100==0:
        print('Epoch {:4d}/{} W:{:.3f}, b: {:.3f} Cost: {:.6f}'.format(epoch, nb_epochs, W.item(),b.item(), cost.item()
                                                                    )) #1개의 원소를 가진 Tensor를 python의 scalar로 만들때는 .item()을 사용한다.
        # d는 정수, f는 부동소수
    

Epoch    0/2000 W:0.403, b: 0.189 Cost: 20.423275
Epoch  100/2000 W:1.738, b: 1.322 Cost: 0.405913
Epoch  200/2000 W:1.580, b: 1.681 Cost: 0.250829
Epoch  300/2000 W:1.456, b: 1.963 Cost: 0.154997
Epoch  400/2000 W:1.359, b: 2.185 Cost: 0.095779
Epoch  500/2000 W:1.282, b: 2.359 Cost: 0.059185
Epoch  600/2000 W:1.222, b: 2.496 Cost: 0.036573
Epoch  700/2000 W:1.174, b: 2.604 Cost: 0.022600
Epoch  800/2000 W:1.137, b: 2.689 Cost: 0.013965
Epoch  900/2000 W:1.108, b: 2.755 Cost: 0.008630
Epoch 1000/2000 W:1.085, b: 2.808 Cost: 0.005333
Epoch 1100/2000 W:1.067, b: 2.849 Cost: 0.003295
Epoch 1200/2000 W:1.052, b: 2.881 Cost: 0.002036
Epoch 1300/2000 W:1.041, b: 2.907 Cost: 0.001258
Epoch 1400/2000 W:1.032, b: 2.927 Cost: 0.000778
Epoch 1500/2000 W:1.025, b: 2.942 Cost: 0.000480
Epoch 1600/2000 W:1.020, b: 2.955 Cost: 0.000297
Epoch 1700/2000 W:1.016, b: 2.964 Cost: 0.000183
Epoch 1800/2000 W:1.012, b: 2.972 Cost: 0.000113
Epoch 1900/2000 W:1.010, b: 2.978 Cost: 0.000070
Epoch 2000/2000 W:1

In [1]:
# 02.자동미분
import torch
w=torch.tensor(2.0,requires_grad=True)
y=w**2
z=2*y+5
z.backward()
print('수식을 w로 미분한 값 : {}',format(w.grad))



수식을 w로 미분한 값 : {} 8.0


In [26]:
#########################################
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)


tensor([ 232.2802,  549.6158, 1331.2263], grad_fn=<MulBackward0>)


In [27]:
v = torch.tensor([1.0, 10000.0, 0.0001], dtype=torch.float) # gradient 값을 scaling 한다

# The tensor passed into the backward function acts like weights for a weighted output of gradient. 
# Mathematically, this is the vector multiplied by the Jacobian matrix of non-scalar tensors 
# (discussed further in this post) hence it should almost always be a unit tensor of dimension same as
# the tensor backward is called upon, unless weighted outputs needs to be calculated.
# tldr : Backward graph is created automatically and dynamically by autograd class during forward pass.
# Backward() simply calculates the gradients by passing its argument to the already made backward graph.

y.backward(v)
print(y.grad)
print(x.grad)
#retain.grad가 머징?
##############################################

None
tensor([1.0240e+03, 1.0240e+07, 1.0240e-01])


In [30]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch. manual_seed(1)

x1_train=torch.FloatTensor([[73],[93],[89],[96],[73]])
x2_train=torch.FloatTensor([[80],[88],[91],[98],[66]])
x3_train=torch.FloatTensor([[75],[93],[90],[100],[70]])
y_train=torch.FloatTensor([[152],[185],[180],[196],[142]])
w1=torch.zeros(1,requires_grad=True)
w2=torch.zeros(1,requires_grad=True)
w3=torch.zeros(1,requires_grad=True)
b=torch.zeros(1, requires_grad=True)
optimizer=optim.SGD([w1,w2,w3,b],lr=1e-5)
nb_epochs=1000
for epoch in range(nb_epochs+1):
    hypothesis=x1_train*w1+x2_train*w2+x3_train*w3+b
    cost=torch.mean((hypothesis-y_train)**2)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    if epoch%100==0:
        print('Epoch {:4d}/{} w1:{:.3f} w2:{:.3f} w3:{:.3f} b:{:.3f} Cost: {:.6f}'.format(epoch, nb_epochs,w1.item(),w2.item(),w3.item(),b.item(), cost.item()))

Epoch    0/1000 w1:0.294 w2:0.294 w3:0.297b:0.003 Cost: 29661.800781
Epoch  100/1000 w1:0.674 w2:0.661 w3:0.676b:0.008 Cost: 1.563634
Epoch  200/1000 w1:0.679 w2:0.655 w3:0.677b:0.008 Cost: 1.497603
Epoch  300/1000 w1:0.684 w2:0.649 w3:0.677b:0.008 Cost: 1.435026
Epoch  400/1000 w1:0.689 w2:0.643 w3:0.678b:0.008 Cost: 1.375730
Epoch  500/1000 w1:0.694 w2:0.638 w3:0.678b:0.009 Cost: 1.319503
Epoch  600/1000 w1:0.699 w2:0.633 w3:0.679b:0.009 Cost: 1.266215
Epoch  700/1000 w1:0.704 w2:0.627 w3:0.679b:0.009 Cost: 1.215693
Epoch  800/1000 w1:0.709 w2:0.622 w3:0.679b:0.009 Cost: 1.167821
Epoch  900/1000 w1:0.713 w2:0.617 w3:0.680b:0.009 Cost: 1.122419
Epoch 1000/1000 w1:0.718 w2:0.613 w3:0.680b:0.009 Cost: 1.079375


In [31]:
x_train=torch.FloatTensor([[73, 80, 75],[93, 88, 93],[89,91,90],[96,98,100],[73,66,70]])
y_train=torch.FloatTensor([[152],[185],[180],[196],[142]])
print(x_train.shape)
print(y_train.shape)
W=torch.zeros((3,1),requires_grad=True) # 여기서 주목할점은 W의 크기가 (3x1)벡터라는 점 x와 행렬곱을 하려면 크기가 이렇게 설정되어야 한다.
b=torch.zeros(1,requires_grad=True)
hypothesis=x_train.matmul(W)+b #여기서 더해주는 b의 크기는 (5x1)의 행렬로 만들어줄 필요가 없다.

torch.Size([5, 3])
torch.Size([5, 1])


In [37]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  90], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

# 모델 초기화
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    # 편향 b는 브로드 캐스팅되어 각 샘플에 더해집니다.
    hypothesis = x_train.matmul(W) + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(epoch, nb_epochs, hypothesis.squeeze().detach(),cost.item()))
    # detach()를 하지 않으면 텐서의 성분만 나오는게 아니라 grad_fn= ??? 까지 같이 나와버린다.
    # if a detach is called then subsequent operations on that view will not be tracked
    # 여기서 .datach() 대신에 .data도 가능
    
        

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([67.2578, 80.8397, 79.6523, 86.7394, 61.6605]) Cost: 9298.520508
Epoch    2/20 hypothesis: tensor([104.9128, 126.0990, 124.2466, 135.3015,  96.1821]) Cost: 2915.712646
Epoch    3/20 hypothesis: tensor([125.9942, 151.4381, 149.2133, 162.4896, 115.5097]) Cost: 915.040527
Epoch    4/20 hypothesis: tensor([137.7968, 165.6247, 163.1911, 177.7112, 126.3307]) Cost: 287.936005
Epoch    5/20 hypothesis: tensor([144.4044, 173.5674, 171.0168, 186.2332, 132.3891]) Cost: 91.371017
Epoch    6/20 hypothesis: tensor([148.1035, 178.0144, 175.3980, 191.0042, 135.7812]) Cost: 29.758139
Epoch    7/20 hypothesis: tensor([150.1744, 180.5042, 177.8508, 193.6753, 137.6805]) Cost: 10.445305
Epoch    8/20 hypothesis: tensor([151.3336, 181.8983, 179.2240, 195.1707, 138.7440]) Cost: 4.391228
Epoch    9/20 hypothesis: tensor([151.9824, 182.6789, 179.9928, 196.0079, 139.3396]) Cost: 2.493135
Epoch   10/20 hypo

In [40]:
import torch
import torch.nn as nn
import torch.nn.functional as F
torch.manual_seed(1)
x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[2],[4],[6]])
model=nn.Linear(1,1)
print(list(model.parameters())) # model.parameters()라는 함수를 사용하여 불러올 수 있습니다.
optimizer=torch.optim.SGD(model.parameters(),lr=0.01)
nb_epochs=2000
for epoch in range(nb_epochs+1):
    prediction=model(x_train)
    cost=F.mse_loss(prediction,y_train)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    if epoch %100==0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))
new_var=torch.FloatTensor([[4.0]])
pred_y=model(new_var)
    

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]
Epoch    0/2000 Cost: 13.103540
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000
훈련 후 입력이 4일 때의 예측값: tensor([[7.9989]], grad_fn=<AddmmBackward>)


In [41]:
print("훈련 후 입력이 4일 때의 예측값:", pred_y)
print(list(model.parameters()))



훈련 후 입력이 4일 때의 예측값: tensor([[7.9989]], grad_fn=<AddmmBackward>)
[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


In [42]:
# H(x) 식에 입력 x로부터 예측된 y를 얻는 것을 forward 연산이라고 합니다.
# 학습 전, prediction = model(x_train)은 x_train으로부터 예측값을 리턴하므로 forward 연산입니다.
# 학습 후, pred_y = model(new_var)는 임의의 값 new_var로부터 예측값을 리턴하므로 forward 연산입니다.
# 학습 과정에서 비용 함수를 미분하여 기울기를 구하는 것을 backward 연산이라고 합니다.
# cost.backward()는 비용 함수로부터 기울기를 구하라는 의미이며 backward 연산입니다.




In [47]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)
x_train=torch.FloatTensor([[73,80,75],[93,88,93],[89,91,90],[96,98,100],[73,66,70]])
y_train=torch.FloatTensor([[152],[185],[180],[196],[142]])
model=nn.Linear(3,1)
print(list(model.parameters())) # 파라미터값들은 모두 랜덤 초기화 되어있음.
optimizer=torch.optim.SGD(model.parameters(),lr=1e-5) # lr이 0.01로 되면 기울기가 발산함
nb_epochs=2000
for epoch in range(nb_epochs+1):
    prediction=model(x_train)
    cost=F.mse_loss(prediction,y_train)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    if epoch % 100==0:
        print('Epoch {:4d}/{} Cost:{:.6f}'.format(epoch,nb_epochs, cost.item()))


[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]
Epoch    0/2000 Cost:31667.597656
Epoch  100/2000 Cost:0.225993
Epoch  200/2000 Cost:0.223911
Epoch  300/2000 Cost:0.221941
Epoch  400/2000 Cost:0.220059
Epoch  500/2000 Cost:0.218271
Epoch  600/2000 Cost:0.216575
Epoch  700/2000 Cost:0.214950
Epoch  800/2000 Cost:0.213413
Epoch  900/2000 Cost:0.211952
Epoch 1000/2000 Cost:0.210559
Epoch 1100/2000 Cost:0.209230
Epoch 1200/2000 Cost:0.207967
Epoch 1300/2000 Cost:0.206762
Epoch 1400/2000 Cost:0.205618
Epoch 1500/2000 Cost:0.204529
Epoch 1600/2000 Cost:0.203481
Epoch 1700/2000 Cost:0.202486
Epoch 1800/2000 Cost:0.201539
Epoch 1900/2000 Cost:0.200634
Epoch 2000/2000 Cost:0.199770


In [50]:
new_var=torch.FloatTensor([[73,80,75]])
pred_y=model(new_var)
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :",pred_y)
print(list(model.parameters()))

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.2306]], grad_fn=<AddmmBackward>)
[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]


In [ ]:
class LinearRegressionModel(nn.Module): # torch.nn.module 이라는 클래스를 상속받는 파이썬 클래스 선언
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(1,1)
    def forward(self):
        return self.linear(x)
    