In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
torch.manual_seed(1)

In [2]:
x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[4],[5],[6]])
# 데이터에 대한 이해 -> 가설 수립-> 손실 계산하기-> 경사 하강법
# 비용 함수(cost function) = 손실 함수(loss function) = 오차 함수(error function) = 목적 함수(objective function)



In [3]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [4]:
print(y_train)
print(y_train.shape)

tensor([[4.],
        [5.],
        [6.]])
torch.Size([3, 1])


In [5]:
W=torch.zeros(1,requires_grad=True) # requir~는 인자로 주어졌으며, 이 변수는 핛브을 통해 값이 게속 변경되는 변수임을 명시
print(W)



tensor([0.], requires_grad=True)
