In [1]:
import torch
It=torch.LongTensor([1,2,3,4])
print(It)


tensor([1, 2, 3, 4])


In [2]:
print(It.float())

tensor([1., 2., 3., 4.])


In [3]:
bt=torch.ByteTensor([True,False,False,True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [4]:
print(bt.long())
print(bt.float())


tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [5]:
x=torch.FloatTensor([[1,2],[3,4]])
y=torch.FloatTensor([[5,6],[7,8]])
print(torch.cat([x,y],dim=0)) #dim=0은 첫번째 차원을 늘리라는 의미를 담음
#2x2 2개가 4x2가 됨

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [8]:
print(torch.cat([x,y],dim=1))
# 2x4가 됨

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [10]:
x=torch.FloatTensor([1,4])
y=torch.FloatTensor([2,5])
z=torch.FloatTensor([3,6])

print(torch.stack([x,y,z]))
print(torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)],dim=0))
# 위 둘은 같은 연산을 실행, stack은 많은 연산을 한번에 할 수 있는 명령어이다.

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [11]:
print(torch.stack([x,y,z],dim=1))
# dim=1은 두번째 차원이 증가하도록 쌓으라는 뜻

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [15]:
x= torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)
print(torch.ones_like(x)) # x shape은 같지만 1로 값이 채워진 텐서 생성
print(torch.zeros_like(x))

tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [17]:
x=torch.FloatTensor([[1,2],[3,4]])
print(x.mul(2.))
print(x)
print(x.mul_(2.)) # 기존 연산에 _를 붙여버리면 x에 붙여쓰기를 해버린다.
print(x)
#matmul은 행렬의 곱셈이지만 *과 mul은 element-wise 곱셈이다.

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


In [18]:
# 파이썬 클래스
result=0
def add(num):
    global result #전역변수 선언했던것을 함수에서 사용하려면 이렇게
    result+=num
    return result
print(add(3))
print(add(4))

3
7


In [ ]:
result1=0
result2=0

def add1(num):
    global result1
    result1 +=num
    return result1

def add2(num):
    global result2
    result2+=num
    return result2
print(add1(3))
print(add1(4))
print(add2(3))
print(add2(4))

In [19]:
class sum:
    def __init__(self):
        self.result=0
    def add(self,num):
        self.result+=num
        return self.result
cal1=sum()
cal2=sum()
print(cal1.add(3))
print(cal1.add(4))
print(cal2.add(3))
print(cal2.add(7))

        

class sum:
    def __init__(self):
        self.result=0
    def add(self, num):
        self.result+=num
        return self.result


        

3
7
3
10
